name: scale25gptr
channels:
  - defaults
dependencies:
  - python=3.11
  - pip=25.0.1
  - pip:
    - beautifulsoup4==4.13.3
    - colorama==0.4.6
    - md2pdf==1.0.1
    - python-dotenv==1.0.1
    - uvicorn==0.34.0
    - pydantic==2.10.6
    - pydantic-settings==2.8.1
    - pydantic_core==2.27.2
    - fastapi==0.115.10
    - python-multipart==0.0.20
    - markdown2==2.5.3
    - langchain==0.3.19
    - langchain-community==0.3.18
    - langchain-core==0.3.40
    - langchain-ollama==0.2.3
    - langchain-openai==0.3.7
    - langchain-text-splitters==0.3.6
    - langchain-openai==0.3.7
    - langchain-ollama==0.2.3
    - langgraph==0.3.2
    - langgraph-checkpoint==2.0.16
    - langgraph-cli==0.1.74
    - langgraph-prebuilt==0.1.1
    - langgraph-sdk==0.1.53
    - tiktoken==0.9.0
    - arxiv==2.1.3
    - PyMuPDF==1.25.3
    - requests==2.32.3
    - requests-toolbelt==1.0.0
    - aiofiles==24.1.0
    - mistune==3.1.2
    - python-docx==1.1.2
    - htmldocx==0.0.6
    - lxml_html_clean==0.4.1
    - websockets==15.0
    - unstructured==0.16.23
    - unstructured-client==0.30.6
    - json_repair==0.39.1
    - json5==0.10.0
    - loguru==0.7.3